// PufferLib 5.0 environment that forwards to a warcraftsim bridge server.
//
// Each Env is one Warcraft III game run by the Python bridge (warcraftsim/puffer/bridge.py). The
// trainer's worker threads call puf_step concurrently; each Env talks to its own server thread over
// a Unix socket, so games step in parallel. $WC3_BRIDGE lists the bridge workers' socket paths
// separated by ';'; environments are assigned to them round-robin in creation order. The including header defines
// OBS_SIZE, NUM_ATNS, ACT_SIZES and WC3_TASK (generated by `python -m warcraftsim.puffer build`).
//
// Protocol (little-endian, all float32 unless noted):
//   hello  -> u32 magic 'W3PF', u32 version, u32 obs_size, u32 num_atns, char task[32]
//          <- u32 num_agents (0 = refused)
//   reset  -> u32 1                      <- obs[num_agents][OBS_SIZE]
//   step   -> u32 2, actions[num_agents][NUM_ATNS]
//          <- obs[num_agents][OBS_SIZE], reward[num_agents], terminal[num_agents],
//             stats[num_agents][4] = {episode ended, return, length, outcome (+1 win, -1 loss, 0 tie)}
#include <errno.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>

#include "raylib.h"
// obs_t (float) is typedef'd by the including header: PufferLib's build script looks for it there.
#include "pufferenv.h"

#define WC3_MAGIC 0x46503357u  // "W3PF"
#define WC3_VERSION 1u
#define WC3_MAX_AGENTS 2

struct Log {
    float episode_return;
    float episode_length;
    float wins;
    float losses;
    float perf;
    float score;
    float n;
};

struct Env {
    Log log;
    Agent agents[WC3_MAX_AGENTS];
    int tag;
    int boundary_reached;
    int num_agents;
    unsigned int rng;
    int fd;
};

static void wc3_io(int fd, void* buf, size_t n, int writing) {
    char* p = (char*)buf;
    while (n > 0) {
        ssize_t k = writing ? write(fd, p, n) : read(fd, p, n);
        if (k < 0 && errno == EINTR) {
            continue;
        }
        if (k <= 0) {
            fprintf(stderr, "wc3: bridge connection lost (%s)\n", k < 0 ? strerror(errno) : "closed");
            exit(3);
        }
        p += k;
        n -= (size_t)k;
    }
}

static void wc3_read_obs(Env* env) {
    for (int a = 0; a < env->num_agents; a++) {
        wc3_io(env->fd, env->agents[a].observations, OBS_SIZE * sizeof(float), 0);
    }
}

static int wc3_env_counter = 0;

void puf_init(Env* env, Dict* kwargs) {
    const char* paths = getenv("WC3_BRIDGE");
    assert(paths && "set WC3_BRIDGE to the bridge servers' socket paths (';'-separated)");
    int n = 1;
    for (const char* c = paths; *c; c++) {
        n += *c == ';';
    }
    int pick = wc3_env_counter++ % n;
    const char* start = paths;
    for (int i = 0; i < pick; i++) {
        start = strchr(start, ';') + 1;
    }
    const char* end = strchr(start, ';');
    size_t len = end ? (size_t)(end - start) : strlen(start);
    env->fd = socket(AF_UNIX, SOCK_STREAM, 0);
    struct sockaddr_un addr = {.sun_family = AF_UNIX};
    assert(len < sizeof(addr.sun_path));
    memcpy(addr.sun_path, start, len);
    for (int attempt = 0;; attempt++) {
        if (connect(env->fd, (struct sockaddr*)&addr, sizeof(addr)) == 0) {
            break;
        }
        assert(attempt < 600 && "bridge server not reachable");
        usleep(100000);
    }
    unsigned int hello[4] = {WC3_MAGIC, WC3_VERSION, OBS_SIZE, NUM_ATNS};
    char task[32] = {0};
    strncpy(task, WC3_TASK, sizeof(task) - 1);
    wc3_io(env->fd, hello, sizeof(hello), 1);
    wc3_io(env->fd, task, sizeof(task), 1);
    unsigned int agents = 0;
    wc3_io(env->fd, &agents, sizeof(agents), 0);
    assert(agents >= 1 && agents <= WC3_MAX_AGENTS && "bridge refused this environment");
    env->num_agents = (int)agents;
    for (int a = 0; a < env->num_agents; a++) {
        env->agents[a].policy = 0;
        env->agents[a].action_mask = NULL;
    }
}

void puf_reset(Env* env) {
    unsigned int cmd = 1;
    wc3_io(env->fd, &cmd, sizeof(cmd), 1);
    wc3_read_obs(env);
}

void puf_step(Env* env) {
    unsigned int cmd = 2;
    wc3_io(env->fd, &cmd, sizeof(cmd), 1);
    for (int a = 0; a < env->num_agents; a++) {
        wc3_io(env->fd, env->agents[a].actions, NUM_ATNS * sizeof(float), 1);
    }
    wc3_read_obs(env);
    float stats[4];
    for (int a = 0; a < env->num_agents; a++) {
        wc3_io(env->fd, env->agents[a].rewards, sizeof(float), 0);
    }
    for (int a = 0; a < env->num_agents; a++) {
        wc3_io(env->fd, env->agents[a].terminals, sizeof(float), 0);
    }
    for (int a = 0; a < env->num_agents; a++) {
        wc3_io(env->fd, stats, sizeof(stats), 0);
        if (stats[0] > 0.5f && a == 0) {
            env->log.episode_return += stats[1];
            env->log.episode_length += stats[2];
            env->log.wins += stats[3] > 0.5f;
            env->log.losses += stats[3] < -0.5f;
            env->log.perf += stats[3] > 0.5f;
            env->log.score += stats[1];
            env->log.n += 1;
        }
    }
}

void puf_render(Env* env) {
}

void puf_close(Env* env) {
    close(env->fd);
}

void puf_log(Log* log, Dict* out) {
    dict_set(out, "episode_return", log->episode_return);
    dict_set(out, "episode_length", log->episode_length);
    dict_set(out, "win_rate", log->wins);
    dict_set(out, "loss_rate", log->losses);
    dict_set(out, "perf", log->perf);
    dict_set(out, "score", log->score);
}
