"""Build the PufferLib 5.0 trainer with a Warcraft III task compiled in.

PufferLib 5.0 compiles its environments into a native CUDA trainer. For a task we generate
``ocean/wc3_<task>/wc3_<task>.h`` (sizes + the shared bridge implementation), copy the pinned
PufferLib checkout (third_party/PufferLib) to build/pufferlib, patch the trainer to append each
epoch's log line to $PUFFER_JSONL (read by the dashboard) and run its build script.
"""

from __future__ import annotations

import hashlib
import shutil
import subprocess
from pathlib import Path

from .. import paths
from .tasks import Task

PUFFER_SRC = paths.REPO_ROOT / "third_party" / "PufferLib"
PUFFER_BUILD = paths.REPO_ROOT / "build" / "pufferlib"
BRIDGE_HEADER = paths.REPO_ROOT / "puffer" / "wc3_bridge.h"

# After the trainer prints its dashboard for an epoch, also append the log dict as JSON.
_JSONL_ANCHOR = "            puf_dashboard_print(ini, pufferl, &new_log, (int)pufferl->epoch);\n"
_JSONL_PATCH = _JSONL_ANCHOR + """            const char* wc3_jsonl = getenv("PUFFER_JSONL");
            FILE* wc3_fp = wc3_jsonl ? fopen(wc3_jsonl, "a") : NULL;
            if (wc3_fp) {
                fprintf(wc3_fp, "{\\"time\\":%.3f", wall_clock());
                for (int wc3_i = 0; wc3_i < new_log.size; wc3_i++) {
                    double wc3_v = new_log.items[wc3_i].value;
                    if (isfinite(wc3_v)) {
                        fprintf(wc3_fp, ",\\"%s\\":%.9g", new_log.items[wc3_i].key, wc3_v);
                    }
                }
                fprintf(wc3_fp, "}\\n");
                fclose(wc3_fp);
            }
"""


def env_name(task: Task) -> str:
    return f"wc3_{task.name}"


def header_text(task: Task) -> str:
    sizes = ", ".join(str(s) for s in task.act_sizes)
    return (f"// Generated by warcraftsim.puffer.build for task {task.name!r}: {task.description}\n"
            f"#define WC3_TASK \"{task.name}\"\n#define OBS_SIZE {task.obs_size}\n"
            f"#define NUM_ATNS {task.num_atns}\n#define ACT_SIZES {{{sizes}}}\n"
            f"#include \"raylib.h\"\ntypedef float obs_t;\n"
            f"#include \"{BRIDGE_HEADER}\"\n")


def _sync_sources() -> None:
    if not (PUFFER_SRC / "build.sh").exists():
        raise FileNotFoundError("third_party/PufferLib missing: git submodule update --init third_party/PufferLib")
    PUFFER_BUILD.mkdir(parents=True, exist_ok=True)
    # anchored excludes: keep build products (downloaded raylib, trainer binaries, build/) across syncs
    subprocess.run(["rsync", "-a", "--exclude", "/.git", "--exclude", "/raylib-*", "--exclude", "/build",
                    "--exclude", "/puffer", "--exclude", "/puffer_*", f"{PUFFER_SRC}/", f"{PUFFER_BUILD}/"],
                   check=True)
    trainer = PUFFER_BUILD / "src" / "pufferl.cu"
    text = trainer.read_text()
    if "PUFFER_JSONL" not in text:
        if _JSONL_ANCHOR not in text:
            raise RuntimeError("pufferl.cu changed: cannot apply the JSON log patch")
        trainer.write_text(text.replace(_JSONL_ANCHOR, _JSONL_PATCH, 1))


def build_trainer(task: Task, force: bool = False) -> Path:
    """Build (if needed) and return the trainer binary for `task`."""
    name = env_name(task)
    header = header_text(task)
    digest = hashlib.sha1((header + BRIDGE_HEADER.read_text()
                           + (PUFFER_SRC / "src" / "pufferl.cu").read_text()).encode()).hexdigest()[:12]
    binary = PUFFER_BUILD / f"puffer_{name}_{digest}"
    if binary.exists() and not force:
        return binary
    _sync_sources()
    env_dir = PUFFER_BUILD / "ocean" / name
    env_dir.mkdir(parents=True, exist_ok=True)
    (env_dir / f"{name}.h").write_text(header)
    config = PUFFER_BUILD / "config" / f"{name}.ini"
    if not config.exists():
        config.write_text(f"[base]\nenv_name = {name}\n")
    result = subprocess.run(["./build.sh", name, binary.name], cwd=PUFFER_BUILD, capture_output=True, text=True)
    if result.returncode != 0 or not binary.exists():
        raise RuntimeError(f"PufferLib build failed:\n{result.stdout[-3000:]}\n{result.stderr[-3000:]}")
    for old in PUFFER_BUILD.glob(f"puffer_{name}_*"):
        if old != binary:
            old.unlink()
    return binary
